apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kong-pg
  namespace: kong
spec:
  # Merge/override valuesContent with auth + persistence
  valuesContent: |-
    auth:
      postgresPassword: "supersecret-postgres"
      username: "kong"
      password: "supersecret-kong"
      database: "kong"

    primary:
      persistence:
        enabled: true
        size: 20Gi