apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

# Use modern 'patches' key
patches:
  - path: deployment-patch.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChart
      name: kong-pg
      namespace: kong
