_format_version: "3.0"
_transform: true
services:
  - host: ts43-auth-backend.ts43.svc.cluster.local
    id: 83f03359-19f7-5f8d-b8c1-e2c8267ebf83
    name: ts43
    path: /
    protocol: http
    port: 80
    retries: 3
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    tags: []
    routes:
      # POST /v2/issue_auth_code
      - id: 82c90817-0bd4-5472-aa79-870d0438732e
        methods:
        - POST
        name: sherlock-api_v2-issue-auth-code_post
        paths:
        - ~/v2/issue_auth_code
        plugins: []
        regex_priority: 200
        strip_path: false
        tags: []

      # GET /v2/authenticate_ts43_client
      - id: 2e6acf9f-7892-5cc6-b8a4-39769531bbab
        methods:
        - GET
        name: sherlock-api_authenticate-ts43-client-v2-authenticate-ts43-client-get
        paths:
        - ~/v2/authenticate_ts43_client
        plugins:
          - name: oauth2
            config:
              scopes:
              - sherlockapiresource/write
              global_credentials: true 
              provision_key: sherlock-api_authenticate-ts43-client-v2-authenticate-ts43-client-get
              enable_client_credentials: true 
        regex_priority: 200
        strip_path: false
        tags: []

      # POST /v2/authenticate_ts43_client (challenge)
      - id: f34b2152-b04e-5b80-9d78-8d096ce1f823
        methods:
        - POST
        name: sherlock-api_challenge-ts43-client-v2-authenticate-ts43-client-post
        paths:
        - ~/v2/authenticate_ts43_client
        plugins: []
        regex_priority: 200
        strip_path: false
        tags: []