apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie-generator
  namespace: kong
  labels:
    app: cookie-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cookie-generator
  template:
    metadata:
      labels:
        app: cookie-generator
    spec:
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/sherlock-004/ts43/cookie-generator-service:v0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # The FastAPI wrapper defaults to this; keep if you used the wrapper I sent
            - name: SCRIPT_PATH
              value: "/app/cookie-generator-service.py"
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      terminationGracePeriodSeconds: 10