apiVersion: v1
kind: Service
metadata:
  name: postgres-kong
  labels:
    app: postgres-kong
spec:
  type: ClusterIP
  selector:
    app: postgres-kong
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
