# k8s/on-perm/patch-env.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie-generator-service
spec:
  template:
    spec:
      containers:
        - name: api
          # Set the required environment variable for the service
          env:
            - name: BACKEND_API_URL
              value: "http://34.54.169.57:80"
            - name: KONG_INTERNAL_OAUTH_URL
              value: "https://kong-kong-proxy.kong.svc.cluster.local:443"
            - name: KONG_ADMIN_URL
              value: "https://kong-kong-admin.kong.svc.cluster.local:8444"
            - name: ISSUE_JWT_URL
              value: "http://jwt-issuer-service.kong.svc.cluster.local:80"