apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: kong
data:
  redis.conf: |
    # Minimal hardening + persistence
    port 6379
    protected-mode yes
    requirepass ${REDIS_PASSWORD}
    appendonly yes
    save 60 1000
    maxmemory 256mb
    maxmemory-policy allkeys-lru
