apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- application.yaml

secretGenerator:
  - name: kong-enterprise-license
    namespace: kong
    files:
      - license=../../../license.json

generatorOptions:
  disableNameSuffixHash: true