# Kong Helm values (base, reused by overlays)
image:
  repository: kong/kong
  tag: "3.7"

env:
  database: "off"              # DB-less mode (no Postgres required)
  router_flavor: "expressions"
  log_level: "info"

# Ingress Controller (needed to watch Ingress/HTTPRoute)
ingressController:
  enabled: true
  installCRDs: true
  env:
    kong_admin_tls_skip_verify: "true"

# Proxy defaults, will be overridden in on-perm overlay
proxy:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 80
  tls:
    enabled: true
    servicePort: 443

# Admin / Manager / Portal are off in base
admin:
  enabled: false

manager:
  enabled: false

portal:
  enabled: false

status:
  enabled: true
