apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kong
  namespace: kong
spec:
  valuesContent: |-
    proxy:
      type: NodePort
      http:
        enabled: true
        servicePort: 80
        nodePort: 32080
      tls:
        enabled: true
        servicePort: 443
        nodePort: 32443
        
    admin:
      type: NodePort
      http:
        enabled: true
        servicePort: 8001
        nodePort: 32081   # pick an open port
      tls:
        enabled: true
        servicePort: 8444
        nodePort: 32441   # pick an open port