apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kong

resources:
  - ../base

helmCharts:
  - name: kong
    repo: https://charts.konghq.com
    version: 2.45.0
    releaseName: kong
    namespace: kong
    valuesFile: values-onperm.yaml
