# On-Prem profile: NodePortr
image:
  repository: kong/kong
  tag: "3.7"

env:
  database: "off"
  router_flavor: "expressions"
  log_level: "info"

ingressController:
  enabled: true
  installCRDs: true
  env:
    kong_admin_tls_skip_verify: "true"

proxy:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    nodePort: 32080   # customer can hit any worker node IP:32080
  tls:
    enabled: true
    servicePort: 443
    nodePort: 32443   # customer can hit any worker node IP:32443

# Keep Admin internal (ClusterIP).  
# Use port-forward or VPN if you need to access it from outside.
admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
  tls:
    enabled: false

status:
  enabled: true
