# camera-auth/k8s/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-auth
  namespace: kong
  labels:
    app: camera-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-auth
  template:
    metadata:
      labels:
        app: camera-auth
    spec:
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/sherlock-004/ts43/camera-auth:v20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # The FastAPI wrapper defaults to this; keep if you used the wrapper I sent
            - name: SCRIPT_PATH
              value: "/app/camera-auth.py"
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      terminationGracePeriodSeconds: 10