apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-auth
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: REDIS_HOST
              value: "ts43-redis.kong.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password
            - name: KONG_INTERNAL_OAUTH_URL
              value: "https://kong-kong-proxy.kong.svc.cluster.local:443"
            - name: EXTERNAL_AUTH_URL
              value: "http://34.54.169.57/v0/authenticate_user" #Update here sherlock LB